### ISSUE TITLE
[Bug] Console Spam

### ISSUE THREAD

**Issue by iiAhmedYT** [MherZaqaryan/BedWars1058-Cosmetics-Issues#114]
**Describe the bug**
This started happening to me out of the blue..
```
[03:19:37 WARN]: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
[03:19:37 WARN]:        at org.sqlite.DB.newSQLException(DB.java:383)
[03:19:37 WARN]:        at org.sqlite.DB.newSQLException(DB.java:387)
[03:19:37 WARN]:        at org.sqlite.DB.execute(DB.java:339)
[03:19:37 WARN]:        at org.sqlite.PrepStmt.executeQuery(PrepStmt.java:75)
[03:19:37 WARN]:        at am.mher.cosmetics.nU8$x32.g3P6HIP.rcxqE5Q(Unknown Source)
[03:19:37 WARN]:        at am.mher.cosmetics.fwMDqsB.hyxdA3b.xBRuyJ$(Unknown Source)
[03:19:37 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(Carbon:64)
[03:19:37 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(Carbon:53)
[03:19:37 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(Carbon:23)
[03:19:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:19:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:19:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**How to reproduce**
1. Just join and play in the server?

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: Paper
 - Software Version: 1.8.8
 - BedWars1058 Version: 23.12.2
 - Cosmetics Addon: [1.2.0 Beta]

**Comment by MherZaqaryan** [comment]
This issue happens rarely, but it happened when you shut your server off while there were players in it, so Cosmetic tried to save a player data while the remote database was already closed, which ended up getting the SQLite database locked, please make sure to kick all the players before shutting the server off.
