### ISSUE TITLE
Glyph issue

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Cosmetics-Issues#15]
****Describe the bug**
the effects dosent work

**How to reproduce**
1.  select any diamond effetcs

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Linux
 - Java: 11
 - Server Software: paper
 - Software Version: 1.14.5
 - BedWars1058 Version: 21.10.1
 - Cosmetics Addon: 1.0.0 (Propants version)

**Additional context**
[21:50:24 WARN]: [BedWars1058-Cosmetics] Task #557 for BedWars1058-Cosmetics v1.0.0 generated an exception
java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftParticle.toNMS(CraftParticle.java:132) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2320) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2310) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2299) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnParticle(CraftWorld.java:2289) ~[patched_1.14.4.jar:git-Paper-245]
        at club.mher.cosmetics.api.VersionSupport.spawnParticle(Unknown Source) ~[?:?]
        at club.mher.cosmetics.api.VersionSupport.spawnColoredParticle(Unknown Source) ~[?:?]
        at club.mher.cosmetics.api.VersionSupport.spawnColoredParticle(Unknown Source) ~[?:?]
        at Z3R_ZPBKs1_6tykcyY_D.q$3AqTWURA6k.F2TvvsZd5$GG7XZ_O(Unknown Source) ~[?:?]
        at Z3R_ZPBKs1_6tykcyY_D.q$3AqTWURA6k.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available in the next 1.0.1 version
