### ISSUE TITLE
error with bed destroy

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Cosmetics-Issues#18]
**Describe the bug**
the squid does not fly and an error is spammed on the console

**How to reproduce**
1. open menu
2. select squid missile

**Screenshots**
![image](https://user-images.githubusercontent.com/85504551/165072148-2b4e32dc-0029-4aa9-8ce4-8f9f3dc70913.png)

**Server Information (please complete the following information):**
- OS: Linux
- Java: 11
- Server Software: paper
- Software Version: 1.14.5
- BedWars1058 Version: 21.10.1
- Cosmetics Addon: 1.0.0 (Propants version)

**Additional context**
[12:28:10 WARN]: [BedWars1058-Cosmetics] Task #38104 for BedWars1058-Cosmetics v1.0.0 generated an exception
net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:ENTITY_ITEM_PICKUP
        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43) ~[patched_1.14.4.jar:git-Paper-245]
        at g$AgUaK$VD5iHZKAE.tMhQLvcA1fuY16x0$AHC.playSound(Unknown Source) ~[?:?]
        at w7sFoxcNg6r82.cpeAfOU_1_$.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by MherZaqaryan** [comment]
This issue has been already fixed and should be available in the next update!

**Comment by MherZaqaryan** [comment]
#13
