### ISSUE TITLE
kill messages

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Cosmetics-Issues#20]
**Describe the bug**
It doesn't open the gui for selecting kill messages

**How to reproduce**
1. Do this...
2. Then that...
3. Will result in...

**Screenshots**

**Server Information (please complete the following information):**
 - OS: linux
 - Server Software: paper
 - Software Version: 1.12.2
 - BedWars1058 Version: 21.10.1
 - Cosmetics Addon:  1.0.0

**Additional context**
console error: 
[17:15:08 ERROR]: Could not pass event InventoryClickEvent to BedWars1058-Cosmetics v1.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1620]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.SNOWBALL
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:71) ~[patched_1.12.2.jar:git-Paper-1620]
        at vLp$8WHXAV.uKp$l2QL25.<init>(Unknown Source) ~[?:?]
        at jW2ko6inr5TI.Qt$MZ8u8CGwU.d_amJ2lAFe$yV_pTEfL(Unknown Source) ~[?:?]
        at lQHMnpLrm0$SzZd_c_sR.RBeLlG00MLr9c.getIcon(Unknown Source) ~[?:?]
        at KYio1$T$8dVDt.kB3rXbwCvi2I.setContents(Unknown Source) ~[?:?]
        at club.mher.cosmetics.api.menu.Menu.open(Unknown Source) ~[?:?]
        at oxDk$hIBi1tmKf.rX_d_P$_2bcE_.onClick(Unknown Source) ~[?:?]
        at bqP1Q$I5H_N7qN.yT$Wi_$X$ubqmGW.fX_Blu_vSKQloXD(Unknown Source) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor564.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 15 more

**Comment by MherZaqaryan** [comment]
This issue is already fixed and should be available in the next update!
