### ISSUE TITLE
[1.14] the plugin dosen't start 

### ISSUE THREAD

**Issue by Propants05** [MherZaqaryan/BedWars1058-Cosmetics-Issues#4]
**Describe the bug**
the plugin dosen't start

**How to reproduce**
1. put the plugin in the plugins folder
2. start the server

**Server Information (please complete the following information):**
 - OS: linux
 - Java Version: 11
 - Server Software: papermc
 - Software Version: 1.14.5
 - BedWars1058 Version: [e.g. 21.10.1]
 - cosmetics Addon: 1.0.0

**Additional context**
error:

[22:58:36] [Server thread/INFO]: [BedWars1058-Cosmetics] Category Projectile Trail registered with 34 cosmetics.
[22:58:36] [Server thread/INFO]: [BedWars1058-Cosmetics] Category Victory Dance registered with 12 cosmetics.
[22:58:36] [Server thread/WARN]: java.lang.ClassFormatError: StackMapTable format error: bad offset for Uninitialized in method 'void urhyYcJG8$bpy6PQca.bsPr$$Ngpp3R1.playEffect(org.bukkit.entity.Player, org.bukkit.entity.Player)'
[22:58:36] [Server thread/WARN]: 	at M$LhivyUDoPA.deGIaX1nvZCdsApk$.registerCosmetics(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at GC$IyrWlPgrpQtJ$Y$5o.l$WMtIP5g_Q_.NOFOK_R$0LjCm6X(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at GC$IyrWlPgrpQtJ$Y$5o.l$WMtIP5g_Q_.<init>(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at club.mher.cosmetics.Cosmetics.f$qI5hZqOX_2cRvP(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:58:36] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:58:36] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:58:36] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:58:36] [Server thread/WARN]: 	at FKN1VRinQY.TpxG_eLauG0cI7fv_fZ2.e0Dnu$phc$wP1fn(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:58:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[22:58:36] [Server thread/WARN]: 	at FKN1VRinQY.TpxG_eLauG0cI7fv_fZ2.rL3ewZF_r$h(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at FKN1VRinQY.TpxG_eLauG0cI7fv_fZ2.aDlObtFnhU$tGP(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at iw_$s_g49wP.Qq$8LsOrH8ilD.O8lhAwS2_Lg7sO0spq(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at club.mher.cosmetics.Cosmetics.onEnable(Unknown Source)
[22:58:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:58:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[22:58:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[22:58:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[22:58:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[22:58:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[22:58:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[22:58:36] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[22:58:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[22:58:36] [Server thread/INFO]: [BedWars1058-Cosmetics] Disabling BedWars1058-Cosmetics v1.0.0

**Comment by MherZaqaryan** [comment]
This issue is fixed and will be available in the next 1.0.1 version.
