### ISSUE TITLE
[Bug] Console Error while executing a command

### ISSUE THREAD

**Issue by SoheylRF** [MherZaqaryan/BedWars1058-Cosmetics-Issues#62]
**Describe the bug**
I just executed a command and the console gave me an error

**How to reproduce**
1. Do /cosmetic menu
2. Got an error

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Windows
 - Server Software: NachoSpigot
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.3

**Additional context**
```
[23:23:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'cosmetic menu' in club.mher.cosmetics.f72_LnX.Tjy_D2_(cosmetic)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1212) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1024) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:880) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:814) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:647) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "club.mher.cosmetics.api.database.IPlayerData.getOwned(String)" because "this.yB0__Ql" is null
        at club.mher.cosmetics.Dn$uOpf.AjpnT6Q.HDD$OtN(Unknown Source) ~[?:?]
        at club.mher.cosmetics.Dn$uOpf.AjpnT6Q.uXSt6My(Unknown Source) ~[?:?]
        at club.mher.cosmetics.Nycrob2.ROz2Fh_.Nkx6zhS(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at club.mher.cosmetics.Nycrob2.ROz2Fh_.setContents(Unknown Source) ~[?:?]
        at club.mher.cosmetics.api.menu.Menu.open(Unknown Source) ~[?:?]
        at club.mher.cosmetics.laMw4MV.CZWinw7.execute(Unknown Source) ~[?:?]
        at club.mher.cosmetics.f72_LnX.Tjy_D2_.execute(Unknown Source) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PandaSpigot-52]
        ... 15 more
```

**Comment by MherZaqaryan** [comment]
This issue has already been fixed and should be available in the next update!
