### ISSUE TITLE
[Bug] Shopkeeper NPC spawning issue

### ISSUE THREAD

**Issue by Squesly** [MherZaqaryan/BedWars1058-Cosmetics-Issues#74]
**Describe the bug**

**How to reproduce**
1. Put the plugin into your plugins folder
2. Run the server and choose Shopkeeper NPC
3. And play

**Screenshots**

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: PaperSpigot (ImanitySpigot)
 - Software Version: 1.8.9
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.0.4
 - Java: 11

**Additional context**
Error:
[05:26:10] [WARN]: [BedWars1058-Cosmetics] Task #145633 for BedWars1058-Cosmetics v1.0.4 generated an exception
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
    at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
    at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
    at club.mher.cosmetics.Dh$Z94G.XVk$Jnc.SFml_zU(Unknown Source) ~[?:?]
    at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
    at club.mher.cosmetics.Dh$Z94G.XVk$Jnc.l05rArc(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1026) ~[spigot.jar:git-iSpigot-PaperEdition]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:501) ~[spigot.jar:git-iSpigot-PaperEdition]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:938) ~[spigot.jar:git-iSpigot-PaperEdition]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:828) ~[spigot.jar:git-iSpigot-PaperEdition]
    at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by MherZaqaryan** [comment]
This issue has already been fixed, and will be available in the next update!

**Comment by heystrombusiness-del** [comment]
can anyone give me 1.8.9 spigot jar
